apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dashboard # This is the default namespace for the application, but you can change it to your desired namespace.project: default
  source:
    repoURL: https://djjudas21.github.io/charts/
    chart: heimdall
    targetRevision: 8.5.1
    helm:
      values: |
        service:
          type: NodePort
          nodePort: 30080
  destination:
    server: https://kubernetes.default.svc
    namespace: heimdall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
