apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://djjudas21.github.io/charts/
    chart: heimdall
    targetRevision: 8.5.1
    helm:
      values: |
        service:
          main:
            ports:
              http:
                port: 80
        ingress:
          main:
            enabled: false
        env:
          TZ: UTC
          PUID: "1000"
          PGID: "1000"
  destination:
    server: https://kubernetes.default.svc
    namespace: dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# filepath: /Users/f.emanuele/Documents/talos-kubernetes-manifests/apps/heimdall.yaml
