spec:
  source:
    helm:
      valuesObject:
        prometheus:
          service:
            type: NodePort
            nodePort: 30090
        grafana:
          service:
            type: NodePort
            nodePort: 30080