apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://savepointsam.github.io/charts
    chart: pihole
    targetRevision: "0.2.0"
    helm:
      valuesObject:
        server:
          service:
            type: NodePort
            dnsTCPNodePort: 30053
            dnsUDPNodePort: 30053
            webNodePort: 30080
        persistence:
          enabled: true
          existingClaim: "pihole"  # Binds to the PVC below
        admin:
          password: "YourStrongAdminPassword"
        dnsmasq:
          customDnsEntries:
            - domain: "fle.api64.de"
              ip: "192.168.1.175"
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi