apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 27.0.2
    helm:
      values: |
        deployment:
          enabled: true

        ingressRoute:
          dashboard:
            enabled: true

        service:
          type: LoadBalancer
          externalTrafficPolicy: Local

        ports:
          web:
            port: 80
            expose:
              default: true
          websecure:
            port: 443
            expose:
              default: true

        additionalArguments:
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--api.dashboard=true"
          - "--certificatesresolvers.le.acme.httpchallenge=true"
          - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
          - "--certificatesresolvers.le.acme.email=your@email.com"
          - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      